version: "3.1"

services:
    db:
        image: mysql
        container_name: groupomania
        restart: always
        environment:
            LANG: C.UTF-8
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./data:/var/lib/mysql

volumes:
    data: